[package]
name = "io-maildir"
description = "Maildir client library for Rust"
version = "0.3.1"
authors = ["Clément DOUIN (soywod) <pimalaya.org@posteo.net>"]
rust-version = "1.87"
edition = "2024"
license = "MIT OR Apache-2.0"
categories = ["email", "filesystem", "no-std"]
keywords = ["email", "maildir", "client", "std", "io-free"]
homepage = "https://pimalaya.org"
documentation = "https://docs.rs/io-maildir/latest/io_maildir"
repository = "https://github.com/pimalaya/io-maildir"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["client", "parser", "serde"]
client = ["dep:gethostname"]
parser = ["dep:mail-parser"]
serde = ["mail-parser?/serde"]

[[example]]
name = "std_store_entry"
path = "examples/std_store_entry.rs"
required-features = ["client"]

[dev-dependencies]
env_logger = "0.11"
tempfile = "3.20"

[dependencies]
gethostname = { version = "1", default-features = false, optional = true }
log = { version = "0.4", default-features = false }
mail-parser = { version = "0.11", default-features = false, optional = true }
thiserror = { version = "2", default-features = false }
